In [ ]:
import torch


In [ ]:
I = torch.arange(8).repeat(8, 1).repeat(2, 1, 1).unsqueeze(0)
I = I.float()
I

tensor([[[[0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.]],

         [[0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.],
          [0., 1., 2., 3., 4., 5., 6., 7.]]]])

In [ ]:
conv = torch.nn.Conv2d(in_channels=2, out_channels=1, kernel_size=2, stride=1)
K = torch.arange(3).repeat(3, 1).repeat(2, 1, 1).unsqueeze(0)
conv.weight.data = K.float()
conv.bias.data = torch.zeros([conv.out_channels])
conv.weight.data
K = K.float()

In [ ]:
result_conv2d_torch = conv(I)
result_conv2d_torch

tensor([[[[ 30.,  48.,  66.,  84., 102., 120.],
          [ 30.,  48.,  66.,  84., 102., 120.],
          [ 30.,  48.,  66.,  84., 102., 120.],
          [ 30.,  48.,  66.,  84., 102., 120.],
          [ 30.,  48.,  66.,  84., 102., 120.],
          [ 30.,  48.,  66.,  84., 102., 120.]]]],
       grad_fn=<ConvolutionBackward0>)

In [ ]:
# 法2

In [ ]:
unfold2 = torch.nn.Unfold(kernel_size=3, padding=0, stride=1)
I_unfold = unfold2(I)
I_unfold

tensor([[[0., 1., 2., 3., 4., 5., 0., 1., 2., 3., 4., 5., 0., 1., 2., 3., 4.,
          5., 0., 1., 2., 3., 4., 5., 0., 1., 2., 3., 4., 5., 0., 1., 2., 3.,
          4., 5.],
         [1., 2., 3., 4., 5., 6., 1., 2., 3., 4., 5., 6., 1., 2., 3., 4., 5.,
          6., 1., 2., 3., 4., 5., 6., 1., 2., 3., 4., 5., 6., 1., 2., 3., 4.,
          5., 6.],
         [2., 3., 4., 5., 6., 7., 2., 3., 4., 5., 6., 7., 2., 3., 4., 5., 6.,
          7., 2., 3., 4., 5., 6., 7., 2., 3., 4., 5., 6., 7., 2., 3., 4., 5.,
          6., 7.],
         [0., 1., 2., 3., 4., 5., 0., 1., 2., 3., 4., 5., 0., 1., 2., 3., 4.,
          5., 0., 1., 2., 3., 4., 5., 0., 1., 2., 3., 4., 5., 0., 1., 2., 3.,
          4., 5.],
         [1., 2., 3., 4., 5., 6., 1., 2., 3., 4., 5., 6., 1., 2., 3., 4., 5.,
          6., 1., 2., 3., 4., 5., 6., 1., 2., 3., 4., 5., 6., 1., 2., 3., 4.,
          5., 6.],
         [2., 3., 4., 5., 6., 7., 2., 3., 4., 5., 6., 7., 2., 3., 4., 5., 6.,
          7., 2., 3., 4., 5., 6., 7., 2., 3., 4

In [ ]:
I_unfold.shape

torch.Size([1, 18, 36])

In [ ]:
K_unfold = unfold2(K).transpose(2, 1)
K_unfold

tensor([[[0., 1., 2., 0., 1., 2., 0., 1., 2., 0., 1., 2., 0., 1., 2., 0., 1.,
          2.]]])

In [ ]:
K_unfold.shape

torch.Size([1, 1, 18])

In [ ]:
result_conv2d_matmul = torch.matmul(K_unfold, I_unfold)
result_conv2d_matmul

tensor([[[ 30.,  48.,  66.,  84., 102., 120.,  30.,  48.,  66.,  84., 102.,
          120.,  30.,  48.,  66.,  84., 102., 120.,  30.,  48.,  66.,  84.,
          102., 120.,  30.,  48.,  66.,  84., 102., 120.,  30.,  48.,  66.,
           84., 102., 120.]]])

In [ ]:
result_conv2d_matmul = result_conv2d_matmul.view(-1, conv.out_channels, 6, 6)
result_conv2d_matmul

tensor([[[[ 30.,  48.,  66.,  84., 102., 120.],
          [ 30.,  48.,  66.,  84., 102., 120.],
          [ 30.,  48.,  66.,  84., 102., 120.],
          [ 30.,  48.,  66.,  84., 102., 120.],
          [ 30.,  48.,  66.,  84., 102., 120.],
          [ 30.,  48.,  66.,  84., 102., 120.]]]])